#!/bin/bash

set -eEux -o pipefail

TARGETS=(x86_64-unknown-linux-gnu)
RELEASE="release"

BIN_RELEASE_TARGETS=(x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu armv7-unknown-linux-gnueabihf)
DEB_RELEASE_TARGETS=(x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu armv7-unknown-linux-gnueabihf)
BIN_WINDOWS_TARGETS=(x86_64-pc-windows-gnu)

build() {
    for target in ${TARGETS[@]}; do
        cargo build -p tftp-binary --target "$target" "--$RELEASE"
        cp target/$target/release/tftp dist/
        cargo build -p tftp-binary --target "$target" "--$RELEASE" --no-default-features --features std
        cargo build -p tftp-binary --target "$target" "--$RELEASE" --no-default-features --features alloc
        cp target/$target/release/tftp dist/tftp-alloc
        cargo build -p tftp-binary --target "$target" "--$RELEASE" --no-default-features --features alloc,encryption,seek
        cargo build -p tftp-binary --target "$target" "--$RELEASE" --no-default-features --features std,encryption
        cargo build -p tftp-binary --target "$target" "--$RELEASE" --no-default-features --features encryption,seek
        cp target/$target/release/tftp dist/tftp-stack-encryption
        cargo build -p tftp-binary --target "$target" "--$RELEASE" --no-default-features --features seek
        cp target/$target/release/tftp dist/tftp-stack
    done

    # cargo build -p tftp-binary --target "x86_64-unknown-linux-musl" "--$RELEASE"
    # cp target/x86_64-unknown-linux-musl/release/tftp dist/tftp-static

    build_deb
}

release_bins() {
    for target in ${BIN_RELEASE_TARGETS[@]}; do

        cross build -p tftp-binary --target "$target" --release --no-default-features --features encryption,seek
        cp target/$target/release/tftp dist/tftp-stack-$target
        # deb depends on this target
        cross build -p tftp-binary --target "$target" --release
        cp target/$target/release/tftp dist/tftp-$target
    done

    for target in ${BIN_WINDOWS_TARGETS[@]}; do
        cross build -p tftp-binary --target "$target" --release
        cp target/$target/release/tftp.exe dist/tftp-$target.exe
        cross build -p tftp-binary --target "$target" --release --no-default-features --features encryption,seek
        cp target/$target/release/tftp.exe dist/tftp-stack-$target.exe
    done
}

release_dist() {
    rm -f ./dist/*
    release_bins

    # cargo build -p tftp-binary --target "x86_64-unknown-linux-musl" "--$RELEASE"
    # cp target/x86_64-unknown-linux-musl/release/tftp dist/tftp-static

    release_deb
    sign
}

release_deb() {
    for target in ${DEB_RELEASE_TARGETS[@]}; do
        cargo deb -p tftp-binary --target $target --no-build --no-strip
        cp target/$target/debian/tftp*.deb dist/
    done
    # cargo deb -p tftp-binary --target x86_64-unknown-linux-musl
    # cp target/x86_64-unknown-linux-musl/debian/tftp_*_amd64.deb dist/
}

sign() {
    cd dist

    local sum_name="SHA512SUMS"
    local sum_path="../target/$sum_name"

    rm -f $sum_name
    rm -f $sum_name.sig
    > $sum_path
    for f in *; do
        sha512sum "$f" >> $sum_path
    done
    cp $sum_path .
    gpg --detach-sign --armor -o "$sum_name.sig" $sum_name
}

$1
