#!/bin/bash

set -eEux -o pipefail

TARGETS=(x86_64-unknown-linux-gnu)
RELEASE="release"

BIN_RELEASE_TARGETS=(x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu armv7-unknown-linux-gnueabihf x86_64-unknown-linux-musl)
DEB_RELEASE_TARGETS=(x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu armv7-unknown-linux-gnueabihf)
BIN_WINDOWS_TARGETS=(x86_64-pc-windows-gnu)

build() {
    mkdir -p dist
    for target in ${TARGETS[@]}; do
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE"
        cp target/$target/release/tftp-dus dist/
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE" --no-default-features --features std
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE" --no-default-features --features alloc
        cp target/$target/release/tftp-dus dist/tftp-dus-alloc
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE" --no-default-features --features alloc,encryption,seek
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE" --no-default-features --features std,encryption
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE" --no-default-features --features encryption,seek
        cp target/$target/release/tftp-dus dist/tftp-dus-stack-encryption
        cargo build -p tftp-std-binary --target "$target" "--$RELEASE" --no-default-features --features seek
        cp target/$target/release/tftp-dus dist/tftp-dus-stack
    done

    # cargo build -p tftp-std-binary --target "x86_64-unknown-linux-musl" "--$RELEASE"
    # cp target/x86_64-unknown-linux-musl/release/tftp-dus dist/tftp-static
}

build_pi() {
    cross build -p tftp-std-binary --target "aarch64-unknown-linux-gnu" --release
}

release_bins() {
    for target in ${BIN_RELEASE_TARGETS[@]}; do

        cross build -p tftp-std-binary --target "$target" --release --no-default-features --features encryption,seek
        cp target/$target/release/tftp-dus dist/tftp-dus-stack-$target
        # deb depends on this target
        cross build -p tftp-std-binary --target "$target" --release
        cp target/$target/release/tftp-dus dist/tftp-dus-$target
    done

    for target in ${BIN_WINDOWS_TARGETS[@]}; do
        cross build -p tftp-std-binary --target "$target" --release
        cp target/$target/release/tftp-dus.exe dist/tftp-dus-$target.exe
        cross build -p tftp-std-binary --target "$target" --release --no-default-features --features encryption,seek
        cp target/$target/release/tftp-dus.exe dist/tftp-dus-stack-$target.exe
    done
}

release_dist() {
    rm -f ./dist/*
    release_bins

    # cargo build -p tftp-std-binary --target "x86_64-unknown-linux-musl" "--$RELEASE"
    # cp target/x86_64-unknown-linux-musl/release/tftp-dus dist/tftp-static

    release_deb
    sign
}

release_deb() {
    if [[ $(docker images -q buster/cargo-deb 2> /dev/null) == "" ]]; then
        docker build -t buster/cargo-deb builder
    fi
    for target in ${DEB_RELEASE_TARGETS[@]}; do
        docker run --mount type=bind,source="$(pwd)",target=/volume --rm buster/cargo-deb -p tftp-std-binary --target $target --no-build --no-strip
        cp target/$target/debian/tftp*.deb dist/
    done
    # cargo deb -p tftp-std-binary --target x86_64-unknown-linux-musl
    # cp target/x86_64-unknown-linux-musl/debian/tftp_*_amd64.deb dist/
}

sign() {
    cd dist

    local sum_name="SHA512SUMS"
    local sum_path="../target/$sum_name"

    rm -f $sum_name
    rm -f $sum_name.sig
    > $sum_path
    for f in *; do
        sha512sum "$f" >> $sum_path
    done
    cp $sum_path .
    gpg --detach-sign --armor -o "$sum_name.sig" $sum_name
}

$1
